config/routes.rb
Rails.application.routes.draw do
  # Resources
  resources :partners
  resources :bookings do
    resource :invoice, only: [:new, :create]
    get 'get_invoice', to: 'bookings#get_invoice', as: :get_invoice
  end

  # Authentication
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  # Background jobs
  resources :jobs, only: [:create]
  # Routes
  get "up" => "rails/health#show", as: :rails_health_check
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get 'switch_locale/:locale', to: 'application#switch_locale', as: :switch_locale
  
  root "home#index"
end

app/models/accommodation.rb
# accommodation.rb
class Accommodation < ApplicationRecord
  belongs_to :partner

  validates :name, presence: true
  validates :sleeping_spots, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :cost_per_night, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :partner
  belongs_to :accommodation
  has_one :invoice

  validates :date_of_stay, presence: true
  validates :amount_of_days, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :partner, presence: true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :booking
  belongs_to :user
end

app/models/partner.rb
class Partner < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :accommodations
  accepts_nested_attributes_for :accommodations, allow_destroy: true
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def switch_locale
    locale = params[:locale]
    if I18n.available_locales.map(&:to_s).include?(locale)
      session[:locale] = locale
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def set_locale
    I18n.locale = session[:locale] || I18n.default_locale
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /bookings or /bookings.json
  def index
    @bookings = current_user.bookings
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = current_user.bookings.build
    @partners = Partner.all
  end

  # GET /bookings/1/edit
  def edit
    @partners = Partner.all
  end

  # POST /bookings or /bookings.json
  def create
    @booking = current_user.bookings.build(booking_params)
    partner = Partner.find(booking_params[:partner_id])
    @accommodation = partner.accommodations.first if partner.accommodations.any?

    @booking.accommodation_id = @accommodation.id if @accommodation

    if @booking.save
      redirect_to @booking, notice: 'Booking was successfully created.'
    else
      @partners = Partner.all
      render :new
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'Booking was successfully updated.'
    else
      @partners = Partner.all
      render :edit
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy
    redirect_to bookings_url, notice: 'Booking was successfully destroyed.'
  end

  def get_invoice
    @booking = Booking.find(params[:booking_id])
    
    CreatePdfJob.perform_async(@booking.id)

    # TODO: make it work that the user receives notification that the invoice is ready. Currently 2 inv
    respond_to do |format|
      format.html { redirect_to booking_path(@booking), notice: 'Invoice PDF is being generated. You will be notified when it is ready.' }
      format.json { render json: { message: 'Invoice PDF is being generated. You will be notified when it is ready.' }, status: :accepted }
    end
  end

  private
    def set_booking
      @booking = current_user.bookings.find(params[:id])
    end
  
    def booking_params
      params.require(:booking).permit(:date_of_stay, :amount_of_days, :partner_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/invoices_controller.rb
# invoice_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate_user!

  def new
    @booking = Booking.find(params[:booking_id])
    @invoice = Invoice.new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @invoice = Invoice.new(invoice_params)
    @invoice.booking = @booking
    @invoice.user = current_user

    if @invoice.save
      redirect_to @booking, notice: 'Invoice was successfully created.'
    else
      render :new
    end
  end

  private

  def invoice_params
    params.require(:invoice).permit(:invoice_number, :amount, :due_date)
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_partner, only: [:show, :edit, :update, :destroy]

  def index
    @partners = Partner.all
  end

  def show

  end

  def new
    @partner = Partner.new
  end

  def edit
  end

  def create
    @partner = Partner.new(partner_params)

    if @partner.save
      redirect_to @partner, notice: 'Partner was successfully created.'
    else
      render :new
    end
  end

  def update
    if @partner.update(partner_params)
      redirect_to @partner, notice: 'Partner was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @partner = Partner.find(params[:id])
    @partner.destroy
    redirect_to partners_url, notice: 'Partner was successfully destroyed.'
  end

  private
  def set_partner
    @partner = Partner.find(params[:id])
  end

  def partner_params
    params
      .require(:partner)
      .permit(:name, :location,
              accommodations_attributes:
                [:id, :name, :sleeping_spots, :cost_per_night, :_destroy])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def about
    end

    def contact
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/bookings/_form.html.haml
= form_with(model: booking, local: true) do |form|
  - if booking.errors.any?
    #error_explanation
      %h2= pluralize(booking.errors.count, "error") + " prohibited this booking from being saved:"
      %ul
        - booking.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :date_of_stay
    = form.date_field :date_of_stay

  .field
    = form.label :amount_of_days
    = form.number_field :amount_of_days

  .field
    = form.label :partner_id, "Partner"
    = form.collection_select :partner_id, @partners, :id, :name

  .flex.items-center.gap-4.mt-6
    = link_to 'Back', bookings_path
    = form.submit

app/views/bookings/edit.html.haml
.flex.md:flex-row.gap-2.md:justify-between.items-center
    %h1 Editing Booking
    = link_to 'View Booking', @booking, class: "btn"

= render 'form', booking: @booking

app/views/bookings/index.html.haml
%h1 Bookings

= link_to 'New Booking', new_booking_path

%table
  %thead
    %tr
      %th Date of Stay
      %th Amount of Days
      %th Partner
      %th{ colspan: 7 }

  %tbody
    - @bookings.each do |booking|
      %tr
        %td= booking.date_of_stay
        %td= booking.amount_of_days
        %td= booking.partner.name
        %td= link_to 'Show', booking
        %td= link_to 'Edit', edit_booking_path(booking)
        %td= link_to 'Invoice', booking_get_invoice_path(booking)
        %td= link_to 'Delete', booking, data: { turbo_method: :delete, turbo_confirm:  'Are you sure?' }

app/views/bookings/new.html.haml
.container
    %h1 New Booking

    = render 'form', booking: @booking

app/views/bookings/show.html.haml
%h1= "Booking ##{@booking.id}"
= link_to 'Back', bookings_path
%p
  %strong Date of Stay:
  = @booking.date_of_stay

%p
  %strong Amount of Days:
  = @booking.amount_of_days

%p
  %strong Staying at our Partner:
  = @booking.partner.name

%p
  %strong Accommodation Details:
  %br
  %p= @booking.accommodation.name
  %br
  %strong Total:
  €
  = @booking.accommodation.cost_per_night * @booking.amount_of_days

%ul
  %li= link_to 'Edit', edit_booking_path(@booking)
  %li= link_to 'Open Invoice', booking_get_invoice_path(@booking)

app/views/home/index.html.haml
- if user_signed_in?
  %body
    .py-6.md:py-12.bg-primary.text-on-primary
      .container
        %hgroup
          %h1.break-words= t('application.name')
          %p= t('booking.description')

        %p.text-lg= t('booking.welcome-message', email: current_user.email)
        %a= link_to t('booking.book-now'), bookings_path

    .ai-tool
      .container.mb-8
        %h2= t('ai-tool.header')
        %p= t('ai-tool.description')
        %a.btn.-primary{href: "#"}= t('ai-tool.try-ai-tool')

- else
  .container.my-8
    %h1= t('auth.welcome')
    %h2= t('auth.sign-up-or-login')

app/views/invoices/create.html.erb
<h1>Invoices#create</h1>
<p>Find me in app/views/invoices/create.html.erb</p>

app/views/invoices/new.html.erb
<h1>Invoices#new</h1>
<p>Find me in app/views/invoices/new.html.erb</p>

app/views/layouts/_footer.html.haml
%footer.bg-primary.text-on-primary.py-4.text-center
  .container
    %nav
      %ul.nav{ style: "list-style: none; padding: 0;" }
        %li.nav-item
          = link_to "Contact", contact_path,  class: 'nav-link'
        %li.nav-item
          = link_to t('application.about'), about_path, class: 'nav-link'
  .mt-4
    %small= raw("&copy; #{Date.today.year} #{t('application.name')}. #{t('application.copyright')}")

app/views/layouts/_header.html.haml
%header.bg-white.text-black.py-4
  .container.flex.gap-4.items-center.justify-between
    = link_to image_tag('bookify-logo.png', { width: 64, height: 64, alt: "Bookify" }), root_path
    %nav.flex.flex-wrap.gap-1
      - if user_signed_in?
        = link_to 'Account', edit_user_registration_path, class: "btn border-none"
        = link_to 'My Bookings', bookings_path, class: "btn border-none"
        = link_to 'Partners', partners_path, class: "btn border-none"
        = link_to "Logout", destroy_user_session_path, method: :delete, class: "btn border-none"
        
      - else
        = link_to "Login", new_user_session_path, class: "btn border-none"
        = link_to "Sign Up", new_user_registration_path, class: "btn border-none"
    = render 'layouts/locale_switcher'

app/views/layouts/_locale_switcher.html.haml
- available_locales = I18n.available_locales.map(&:to_s)
- current_locale = I18n.locale.to_s
- other_locales = available_locales - [current_locale]

%div.locale-switcher
  - other_locales.each do |locale|
    = link_to locale.upcase, switch_locale_path(locale), class: 'btn btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head{lang: I18n.locale }
    %title Bookify
    %meta{name: "description", content: "Your place for booking your stay during the holidays. Don't know what to do in the area? Try our AI suggestion tool!"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %meta{charset: "utf-8"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "data-turbo-track": "reload"
    = javascript_importmap_tags

  %body.flex.flex-col
    = render 'layouts/header'
    - if current_page?(root_url)
      %main.flex-grow
        = yield
    - else
      %main.container.flex-grow.my-8.max-w-prose
        = yield

    = render 'layouts/footer'

app/views/partners/_accommodation_fields.html.haml
.nested-fields
  %div
    = accommodation_fields.label :name
    = accommodation_fields.text_field :name
  %div
    = accommodation_fields.label :sleeping_spots
    = accommodation_fields.number_field :sleeping_spots
  %div
    = accommodation_fields.label :cost_per_night
    = accommodation_fields.number_field :cost_per_night

app/views/partners/edit.html.haml
%h1 Edit Partner

= form_with(model: @partner, local: true) do |form|
  - if @partner.errors.any?
    #error_explanation
      %h2= pluralize(@partner.errors.count, "error") + " prohibited this partner from being saved:"
      %ul
        - @partner.errors.full_messages.each do |message|
          %li= message

  %div
    = form.label :name
    = form.text_field :name
  %div
    = form.label :location
    = form.text_field :location

  %h2 Accommodation
  #accommodations
    = form.fields_for :accommodations do |accommodation_fields|
      = render 'accommodation_fields', accommodation_fields: accommodation_fields

  -# TODO: make this work so multiple new accommodation can be added
  -# %div
  -#   = link_to 'Add Accommodation', '#', id: 'add_accommodation', class: 'button'

  %div
    = form.submit "Update Partner"

= link_to 'Back', partners_path

app/views/partners/index.html.haml
%h1 Partners
= link_to 'New Partner', new_partner_path
%table
  %thead
    %tr
      %th Partner
      %th Location
      %th 
      %th{ colspan: 4 }
  %tbody
    - @partners.each do |partner|
      %tr
        %td= link_to partner.name, partner_path(partner)
        %td= partner.location
        %td= link_to 'Edit', edit_partner_path(partner)
        %td= link_to 'Destroy', partner_path(partner), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }

      

app/views/partners/new.html.haml
%h1 New Partner

= form_with(model: @partner, local: true) do |form|
  - if @partner.errors.any?
    #error_explanation
      %h2= pluralize(@partner.errors.count, "error") + " prohibited this partner from being saved:"
      %ul
        - @partner.errors.full_messages.each do |message|
          %li= message

  %div
    = form.label :name
    = form.text_field :name
  %div
    = form.label :location
    = form.text_field :location

  %h2 Accommodation
  #accommodations
    = form.fields_for :accommodations, @partner.accommodations.build do |accommodation_fields|
      = render 'accommodation_fields', accommodation_fields: accommodation_fields

  -# TODO: make this work so multiple new accommodation can be added
  -# %div
  -#   = link_to 'Add Accommodation', '#', id: 'add_accommodation', class: 'button'

  .mt-6.flex.items-center.gap-4
    = link_to 'Back', partners_path
    = form.submit "Create Partner"

app/views/partners/show.html.haml
%h1= @partner.name
%p
  Location:
  = @partner.location

%h2 Accommodations
%table
  %thead
    %tr
      %th Name
      %th Sleeping Spots
      %th Cost per Night
  %tbody
    - @partner.accommodations.each do |accommodation|
      %tr
        %td= accommodation.name
        %td= accommodation.sleeping_spots
        %td= accommodation.cost_per_night

= link_to 'Edit', edit_partner_path(@partner)
|
= link_to 'Back', partners_path

app/views/static_pages/about.html.haml
%h1= t 'about.title'
%p= t 'about.introduction'
%p= t 'about.technology-and-tools'
%p= t 'about.inclusivity'
%p= t 'about.cta'

app/views/static_pages/contact.html.haml
%h1= t('contact.header')
%p= t('contact.introduction')
%h2.text-lg.mb-1= t('contact.address-header')
%Address.mt-1
  = t('contact.company-name')
  %br
  = t('contact.address')
  %br
  = t('contact.postal-code')
  %br
  = t('contact.country')
%p= t('contact.email')
%p= t('contact.phone')